apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: express-ci
spec:
  params:
    - name: git-repo
      type: string
    - name: image-repo
      type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.git-repo)
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: pipeline-shared-data

  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
      - git-clone
    workspaces:
      - name: source
        workspace: pipeline-shared-data
    params:
    - name: IMAGE
      value: "$(params.image-repo):$(tasks.git-clone.results.commit)"

  workspaces:
    - name: pipeline-shared-data
